name: CI

on: pull_request

jobs:
    format-code:
        uses: artisanelevated/workflows/.github/workflows/format-js-code.yml@main

    run-e2e-tests:
        needs: [format-code]
        uses: artisanelevated/workflows/.github/workflows/run-playwright-test.yml@main

    dependabot:
        needs: [run-e2e-tests]
        uses: artisanelevated/workflows/.github/workflows/dependabot-automerge.yml@main